### ISSUE TITLE
一起开源给物联网各界开发者使用

### ISSUE THREAD

**Issue by xuhongv** [tencentyun/qcloud-iot-esp-wifi#1]
- 我是深圳安信可科技公司的在职人员，我们有出产 ESP8266-12F 这样优秀的模组，想集合贵司的此方案结合一起开源给物联网各界开发者使用，如有兴趣，请联系我；

- xuhongv@aithinker.com

**Comment by xcguang** [comment]
https://www.espressif.com/zh-hans/support/download/at

乐鑫官方也有一套固件
<img width="911" alt="image" src="https://user-images.githubusercontent.com/25979965/77393588-4965e700-6dd8-11ea-9ad2-046350398cfc.png">

**Comment by xuhongv** [comment]
了解。我现在已经成功编译运行了！如需一起推广，可以联系我！

---深圳安信可科技公司

**Comment by spikelin** [comment]
AT固件以及开源的代码都可以直接在ESP8266-12F上面使用
