### ISSUE TITLE
不管怎么编译都不通过,求大牛

### ISSUE THREAD

**Issue by hmuyin** [tencentyun/qcloud-iot-esp-wifi#14]
CC build/main/ota_esp/qcloud_iot_ota_esp.o
E:/Espressif/msys32/home/hmuyin/ESP8266_RTOS_SDK/APP/qcloud-iot-esp8266-demo/main/ota_esp/qcloud_iot_ota_esp.c: In function 'enable_ota_task':
E:/Espressif/msys32/home/hmuyin/ESP8266_RTOS_SDK/APP/qcloud-iot-esp8266-demo/main/ota_esp/qcloud_iot_ota_esp.c:513:5: error: 'memset' writing 36 bytes into a region of size 32 overflows the destination [-Werror=stringop-overflow=]
     memset(sg_ota_ctx.local_version, 0, MAX_SIZE_OF_FW_VERSION + 4);
     ^~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~
cc1.exe: some warnings being treated as errors
make[1]: *** [/home/hmuyin/ESP8266_RTOS_SDK/make/component_wrapper.mk:292：ota_esp/qcloud_iot_ota_esp.o] 错误 1
make: *** [E:/Espressif/msys32/home/hmuyin/ESP8266_RTOS_SDK/make/project.mk:571：component-main-build] 错误 2

**Comment by spikelin** [comment]
把513行那个 memset(sg_ota_ctx.local_version, 0, MAX_SIZE_OF_FW_VERSION + 4); 改为 memset(sg_ota_ctx.local_version, 0, MAX_SIZE_OF_FW_VERSION);
这里可能哪个版本merge时候没同步好
