### ISSUE TITLE
建议增加获取设备所在地天气信息的能力，比如当地温度、湿度、日出日落时间、空气质量，风速

### ISSUE THREAD

**Issue by jopny** [tencentyun/qcloud-iot-esp-wifi#3]
湿度：烘干储存类设备需要
日出日落时间：照明设备需要
空气质量：新风系统

**Comment by spikelin** [comment]
这类应用层数据的获取需要用户根据需求自行写代码实现。

**Comment by jopny** [comment]
这种需求是智能化场景比较常见的需求，模块要接到你们的后台，从后台获取数据才行，如果再接第三方平台，势必降低可靠性，并且属于重复性开发。低于第三方来言，需要搞定地理位置识别，需要购买全球天气数据，并不容易。
