### ISSUE TITLE
如何获取模块状态信息，以便在设备端显示

### ISSUE THREAD

**Issue by jopny** [tencentyun/qcloud-iot-esp-wifi#4]
可能的状态：
AP配网/SmartConfig配网/正常
已连接路由/断开无线/连接路由中/超时，密码错误，信号弱
已连接服务器（具备提供服务能力）/超时，DNS错误

WiFi信号强度
连通性测试

**Comment by spikelin** [comment]
部分状态可通过ESP SDK的接口或者ESP AT接口获取
