### ISSUE TITLE
20个以上的数据点,长Json消耗资源太多，底板MCU很难处理，建议定义一套串口通讯协议

### ISSUE THREAD

**Issue by jopny** [tencentyun/qcloud-iot-esp-wifi#5]
1. 定义一套串口通讯协议
2. 用源代码自动生成的方式，依据profile生成MCU端SDK

设备厂家的开发水平参差不齐，这些如果都做好了，设备厂家就可以快速集成，再加上OTA和迭代使固件成熟度越来越高。

如果允许各厂家自行开发，是有足够的开放性，但平台就要提供实验室对各厂家自行开发的固件进行测试验证，并发放认证证书，以确保联网设备的质量。

**Comment by spikelin** [comment]
基于二进制数据的模组串口通讯协议正在规划中，敬请期待
