### ISSUE TITLE
Can device property be float?

### ISSUE THREAD

**Issue by dongbh** [tencentyun/qcloud-iot-esp-wifi#7]
I just develop a prog using light_data_template_sample.c as following steps:
1, create a device such as TempHumidity;
2,generate data_config.c;
3,merge it into light_data_template_sample.c;
4,change cycle_report();
......

IF device property(eg, Humidity) is INT, everything is OK.
But if set the property to FLOAT, the mqtt publish will fail, for there is no value for property KEY
----------------------
BG|2020-07-25 11:34:33|mqtt_client_publish.c|qcloud_iot_mqtt_publish(345): publish packetID=0|topicName=$thing/up/property/XXXXXXXXX/device01|payload={"method":"report", "clientToken":"XXXXXXXX-26", "params":{"HCHO":}}

**Comment by spikelin** [comment]
FLOAT should be supported. Can you pls show more running log about the failure?

**Comment by dongbh** [comment]
Thanks for your reply.
Here is what I did:
1, add a custom property into wifi light example:  Temperature,float, from -100.00 to +100.00 step .01;
2, sample code part 1:
#define TOTAL_PROPERTY_COUNT 5
#define MAX_STR_NAME_LEN     (64)
......
typedef struct _ProductDataDefine {
    TYPE_DEF_TEMPLATE_BOOL   m_light_switch;
    TYPE_DEF_TEMPLATE_ENUM   m_color;
    TYPE_DEF_TEMPLATE_INT    m_brightness;
    TYPE_DEF_TEMPLATE_STRING m_name[MAX_STR_NAME_LEN + 1];
    TYPE_DEF_TEMPLATE_FLOAT m_Temperature;
} ProductDataDefine;

static ProductDataDefine sg_ProductData;

static void _init_data_template(void)
{
    memset((void *)&sg_ProductData, 0, sizeof(ProductDataDefine));

    sg_ProductData.m_light_switch         = 0;
    sg_DataTemplate[0].data_property.key  = "power_switch";
    sg_DataTemplate[0].data_property.data = &sg_ProductData.m_light_switch;
    sg_DataTemplate[0].data_property.type = TYPE_TEMPLATE_BOOL;
......
    sg_ProductData.m_Temperature = 0;
    sg_DataTemplate[4].data_property.data = &sg_ProductData.m_Temperature;
    sg_DataTemplate[4].data_property.key  = "Temperature";
    sg_DataTemplate[4].data_property.type = TYPE_TEMPLATE_;
};

3, sample code part 2:
/*example for cycle report, you can delete this for your needs*/
static void cycle_report(Timer *reportTimer)
{
    int i;

    if (expired(reportTimer)) {
        for (i = 0; i < TOTAL_PROPERTY_COUNT; i++) {
            DeviceProperty *pReportData = &(sg_DataTemplate[i].data_property);
            /* simulate brightness changes */
            if (0 == strcmp(pReportData->key, "brightness")) {
                int *brightness = (int *)pReportData->data;
                *brightness += 5;
                if (*brightness > 100)
                    *brightness = 0;

                set_propery_state(pReportData->data, eCHANGED);
            } else {
                set_propery_state(&(sg_DataTemplate[i].data_property.data), eCHANGED);
            }

            if (0 == strcmp(pReportData->key, "Temperature")) {
                float *t = (float *)pReportData->data;
                *t += 5.10;
                if (*t > 100)
                    *t = 0;

                set_propery_state(pReportData->data, eCHANGED);
            } else {
                set_propery_state(&(sg_DataTemplate[i].data_property.data), eCHANGED);
            }


        }
        countdown_ms(reportTimer, 10000);
        
    }
}

4, debug output
DBG|2020-08-02 10:34:37|data_template_client.c|_get_status_reply_ack_cb(215): Received Json Document={"method":"get_status_reply","clientToken":"8VCA202PA8-1","code":0,"status":"success","data":{"reported":{"brightness":35,"power_switch":0,"Temperature":35,"color":0}}}
DBG|2020-08-02 10:34:37|light_data_template_sample.c|qcloud_iot_explorer_demo(656): Get data status success

[  light is off ]|[brightness:--------------------]|[device1]

DBG|2020-08-02 10:34:37|mqtt_client_subscribe.c|qcloud_iot_mqtt_subscribe(147): topicName=$ota/update/8VCA202PA8/device1|packet_id=19524
DBG|2020-08-02 10:34:38|data_template_client.c|_template_mqtt_event_handler(269): template subscribe success, packet-id=19524
INF|2020-08-02 10:34:38|light_data_template_sample.c|event_handler(316): subscribe success, packet-id=19524
DBG|2020-08-02 10:34:38|ota_mqtt.c|_otamqtt_event_callback(124): OTA topic subscribe success
INF|2020-08-02 10:34:38|ota_client.c|IOT_OTA_ResetStatus(136): reset OTA state!
DBG|2020-08-02 10:34:38|mqtt_client_publish.c|qcloud_iot_mqtt_publish(339): publish topic seq=19525|topicName=$ota/report/8VCA202PA8/device1|payload={"type": "report_version", "report":{"version":"1.0.0"}}
INF|2020-08-02 10:34:38|qcloud_iot_ota_esp.c|_ota_update_task(275): start ota update task!
INF|2020-08-02 10:34:38|light_data_template_sample.c|event_handler(330): publish success, packet-id=19525
DBG|2020-08-02 10:34:38|ota_mqtt.c|_otamqtt_upgrage_cb(110): topic=$ota/update/8VCA202PA8/device1
INF|2020-08-02 10:34:38|ota_mqtt.c|_otamqtt_upgrage_cb(111): len=86, topic_msg={"result_code":0,"result_msg":"success","type":"report_version_rsp","version":"1.0.0"}
INF|2020-08-02 10:34:38|ota_client.c|_ota_callback(103): Report version success!
DBG|2020-08-02 10:34:49|mqtt_client_publish.c|qcloud_iot_mqtt_publish(345): publish packetID=0|topicName=$thing/up/property/8VCA202PA8/device1|payload={"method":"report", "clientToken":"8VCA202PA8-2", "params":{"brightness":5,"Temperature":}}
INF|2020-08-02 10:34:49|light_data_template_sample.c|qcloud_iot_explorer_demo(729): data template report success
DBG|2020-08-02 10:34:49|data_template_client_manager.c|_on_template_downstream_topic_handler(512): recv:json format illegal
ERR|2020-08-02 10:34:49|data_template_client_manager.c|_on_template_downstream_topic_handler(516): Fail to parse method!
DBG|2020-08-02 10:34:59|mqtt_client_publish.c|qcloud_iot_mqtt_publish(345): publish packetID=0|topicName=$thing/up/property/8VCA202PA8/device1|payload={"method":"report", "clientToken":"8VCA202PA8-3", "params":{"brightness":10,"Temperature":}}
INF|2020-08-02 10:34:59|light_data_template_sample.c|qcloud_iot_explorer_demo(729): data template report success
DBG|2020-08-02 10:34:59|data_template_client_manager.c|_on_template_downstream_topic_handler(512): recv:json format illegal
ERR|2020-08-02 10:34:59|data_template_client_manager.c|_on_template_downstream_topic_handler(516): Fail to parse method!

5, If I change line 63 and line 98 from FLOAT to INT, everything works OK!

6, source file attached here.
[light_data_template_sample.c.zip](https://github.com/tencentyun/qcloud-iot-esp-wifi/files/5011559/light_data_template_sample.c.zip)

**Comment by spikelin** [comment]
I can reproduce your issue in my ESP8266 environment...

The reason of this error is because **ESP8266 RTOS SDK don't support float print**. Check below page for reference.
https://blog.csdn.net/gengyuchao/article/details/91358347

**There is a workaround if you only need a read-only data property:**
```
--- a/qcloud-iot-esp8266-demo/components/qcloud_iot/qcloud_iot_c_sdk/sdk_src/data_template_client_json.c
+++ b/qcloud-iot-esp8266-demo/components/qcloud_iot/qcloud_iot_c_sdk/sdk_src/data_template_client_json.c
@@ -136,7 +136,13 @@ int put_json_node(char *jsonBuffer, size_t sizeOfBuffer, const char *pKey, void
         } else if (type == JDOUBLE) {
             rc_of_snprintf = HAL_Snprintf(jsonBuffer + strlen(jsonBuffer), remain_size, "%f,", *(double *)(pData));
         } else if (type == JFLOAT) {
-            rc_of_snprintf = HAL_Snprintf(jsonBuffer + strlen(jsonBuffer), remain_size, "%f,", *(float *)(pData));
+            // ESP SDK don't support float print, below code is a workaround and precision is only %.2f
+            int integer = *(float *)(pData);
+            double decimals = (*(float *)(pData) - integer);
+            int decimals_int = (int)(decimals*100);
+            if (decimals_int < 0)
+                decimals_int *= -1;
+            rc_of_snprintf = HAL_Snprintf(jsonBuffer + strlen(jsonBuffer), remain_size, "%d.%02d,", integer, decimals_int);
         } else if (type == JBOOL) {
             rc_of_snprintf =
                 HAL_Snprintf(jsonBuffer + strlen(jsonBuffer), remain_size, "%s,", *(bool *)(pData) ? "true" : "false");
```
But if you need a read-write property, then you have to make more workaround to function _direct_update_value to handle float input...

**Comment by dongbh** [comment]
Thanks for your great work!
