### ISSUE TITLE
使用AT版的，如何进行量产

### ISSUE THREAD

**Issue by wenkumk** [tencentyun/qcloud-iot-esp-wifi#9]
如果使用esp8266(at)+mcu，如何量产，现在使用的是密匙认证，这样需要一个一个写入，如果需要量产，使用那种认证方式呢？

**Comment by ospanic** [comment]
通过AT指令一个个的写入肯定不现实，安信可 科技免费提供秘钥写入服务，什么三元组，uuid，激活码，MAC地址都可以写入，你可以了解下

**Comment by spikelin** [comment]
我们有用于量产的工具可以生成三元组的bin文件，有需要请在腾讯云物联网产品上提工单服务

**Comment by ospanic** [comment]
将三元组生成Bin文件，然后烧录到Flash，这也是一种方法。但是这样的话要生成很多Bin文件，管理起来会很麻烦。
比较理想的做法是通过数据库管理所有的三元组，烧录的时候从数据库中取出一天三元组，烧录到模块中，然后再记录下这个三元组何时何地用在了哪个模块上，便于后期追查问题。也能防止三元组重复使用。
